name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Descargar el código del repositorio
      - name: Check out the code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Configurar variables de entorno (opcional)
      - name: Configurar variables de entorno
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: echo "Variables de entorno configuradas"

      # Construcción y pruebas (si aplican)
      - name: Build and Test
        run: |
          npm run build # Cambia este comando según tu proyecto
          echo "Pruebas completadas"

      # Desplegar con FTP
      - name: Deploy to cPanel with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.5.0 # Actualiza la versión según sea necesario
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./ # Cambia si necesitas subir un subdirectorio específico
          server-dir: /home/cablesur/cablesurinternet.com # Ruta de destino en tu hosting

